# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Forward Filtering - SingleStep
#'
#' @export
forward_filter <- function(Y, G, P, V, W, m, C, nu, Psi) {
    .Call(`_spFFBS_forward_filter`, Y, G, P, V, W, m, C, nu, Psi)
}

forward_filter_T <- function(Y, G, P, V, W, prior) {
    .Call(`_spFFBS_forward_filter_T`, Y, G, P, V, W, prior)
}

#' Backward Sampling - SingleStep
#'
#' @export
backward_sample <- function(G, P, V, W, ForwFilt, ThetaSmp, SigmaSmp, t, L) {
    .Call(`_spFFBS_backward_sample`, G, P, V, W, ForwFilt, ThetaSmp, SigmaSmp, t, L)
}

backward_sample_T <- function(G, P, V, W, ForwFilt, L) {
    .Call(`_spFFBS_backward_sample_T`, G, P, V, W, ForwFilt, L)
}

